### ISSUE TITLE
Components To Build

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#106]
These are components that we will need to build to make the application modular and testable.  This list is subject to change, and each component should be described in its own issue.
#### Components
- [x] ~~Loading Button (Issue: #57, PR #194)~~
- [x] ~~Edit Date Component (Issue: #58, PR: #102)~~
- [ ] Loading Indicator (Issue: #68)
- [x] ~~Find Patient Component (Issue: #69, PRs: #116, #132)~~
- [x] ~~Find Debtor Group Component (PR #134)~~
- [ ] Find Account Component
- [x] ~~Location Selection Component (Issue: #35, PR #108)~~
- [ ] Signature Component (Issue: #78)
- [x] ~~Headercrumb Component (PR #107)~~
- [ ] UI Grid Status Indicator
- [x] ~~Cashbox Select Component (PR #119)~~
- [x] ~~Location Modal (Issue: #100, PR #136)~~
- [ ] Currency Select Component (PR #178)

**Comment by jniles** [comment]
@sfount are we still needing the year/date selection component?  Or will patient registration handle that case itself?  Is the year/date pattern used anywhere else?

**Comment by sfount** [comment]
The pattern is not used anywhere else. No design was ever put together for this component so there is no problem with removing it.

**Comment by jniles** [comment]
Okay, sounds good.

**Comment by jniles** [comment]
I'll tackle the "UI Grid Status Indicator" next.

**Comment by jniles** [comment]
Closing this as irrelevant.
