### ISSUE TITLE
(feature) Stock Additional Features to implements

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1484]
This issue is about feature to add for stock management : 

- [x] Add accounting entries for all stock operations (entry, exit, adjustment) #1488
- [x] Add depots management with the consideration of service's depot #1489
- [ ] Add donor and donation management #1490
- [ ] Add registries :  
  * [ ] Consumption registry (cahier des consommaitons) #1485 
  * [ ] Patient distribution registry #1486
  * [ ] Service distribution registry #1487

**Comment by mbayopanda** [comment]
@sfount , @jniles , @lomamech , @DedrickEnc 
Here is a list of some core features that we must implement for stock. Feel free to give your suggestions, enhancement or any other feedback.

**Comment by jniles** [comment]
@mbayopanda, looks good! :+1:

Do we need to separate out the Patient Distribution, Service, and Consumption registries?  How different will they be?

**Comment by mbayopanda** [comment]
@jniles those registries  are independent, so by separating them we can improve the time of implementation because we can assign the three registry to three developer.

And i think, the consumption registry can be more complex than others and it can take more time.
