### ISSUE TITLE
(refactor) Improvements to Fiscal Year

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1646]
In order to have opening balances properly calculated, we need to address how to open, close, and adjust fiscal years.  The Fiscal Year module is showing its age, and needs to benefit from a few cosmetic improvements before the logic can be cleanly addressed.
 - [x] Use `translate` directive instead of `$translate` filter (#1074)
 - [x] Use `headercrumb` modal headers
 - [x] Use `ngModelOptions` to prevent many $digest loops (#1284).
 - [x] Use the `bhAccountSelect` component (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1013)
 - [x] Deprecate usage of `bhFormDefaults` (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1447).

**Comment by jniles** [comment]
All these have been progressively tackled in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1627, https://github.com/IMA-WorldHealth/bhima-2.X/pull/1840, and https://github.com/IMA-WorldHealth/bhima-2.X/pull/1650.
