### ISSUE TITLE
Login - 2.x Review

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#222]
This issue documents the updates to the bhima login page that need to be made before the page is up to bhima-2.X standards.
##### App Structure/css
- [x] ~~Login form should be centered vertically on any screen size (using `vh` css properties)~~
- [x] Login Form should be centered vertically in line with the sidebar, not the screen vertical center.
- [x] Redesign the panel-heading for clearer login message
- [x] Remove duplicate text on the login page introduced in #283 and #197.
- [x] Login form should expand to full screen on small screen size.
##### Form Validation
- [x] Login form should clearly distinguish between server-sent errors and client side errors.
- [x] Find a better place for "Forgot your password?" text.
##### End-to-End Tests
- [x] Write tests to demonstrate the following capabilities:
  - [x] Login to a particular project (assert that the project name is correct)
  - [x] Page Refresh retains login
  - [x] Login and Logout, page refresh retains logout
  - [x] Invalid username/password credentials display informative errors
##### Error Handling
- [x] Application errors (no enterprises, no projects, etc) should be CLEARLY put above the login form, perhaps disabling the login capabilities.  These should be checked when the application starts. **Use `growl-notifications` introduced in #370**
- [x] Errors from HTTP should be CLEARLY displays above the login form, along with appropriate translations and error codes. **Use `growl-notifications` introduced in #370**
- [x] Form errors should be displayed beneath the form and prompt the user to resubmit with different credentials.
##### Cache
- [x] The login form should remember (and select) the last project used on that computer.
##### Documentation
- [x] Code should produce a readable JSDoc document for future reference.
##### Service Architecture
- [x] Login/Logout functionality should exist in a separate service, not in the Login controller itself.

With these improvements, the Login Form should be pretty close to bhima-2.x's standards.

**Comment by jniles** [comment]
Note: updates on 4/5/2016.

**Comment by sfount** [comment]
The updates here LGTM - this would be a logical component to tackle first. 

The ideas for error handling sound very useful 👍

**Comment by jniles** [comment]
Alright, I'll tackle this today.

**Comment by jniles** [comment]
Critical bug - the URL navigation still works when the user doesn't have a session.  Steps to reproduce:
1. Load the login page.
2. Type `#/settings` into the URL.
3. Observe that while the URL reset to `#/login`, you will be looking at the Settings page.

**Comment by sfount** [comment]
Interesting - that must mean the only redirect that actually works is on an unauthenticated HTTP request. The settings page only makes a request to `/languages` which happens to be defined as a public route so it doesn't throw the error causing a redirect. 

Most of the other pages do!

**Comment by jniles** [comment]
Yes, I found the bug and fixed it in https://github.com/jniles/bhima-2.X/commit/fe8ed51a94e11628bf17931843160bba3495e1b6.  It was a fairly easy fix - we had not updated our session safeguards for `$state`-based routing, which knows nothing of the URL.  Now, we use the `$state` to redirect in case the URL is invalid...  Slightly hard-coded, but good enough for now, I think.

I'll write some end-to-end tests and confirm that everything  behaves as expected before sending in a pull request.
