### ISSUE TITLE
(stock) Issues related to stock management for enterprise assets

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2383]
This set of issues are found when we have tried to run stock management for handling IMA/IMT assets.

- [x] Edit account in inventory group doesn't work #2376
- [x] Inventory list doesn't refresh the grid after adding  a new inventory when the option `add another` is activated #2377
- [x] Some inventory doesn't not need expiration date #2378
- [x] Handle correctly individual inventory #2379
- [x] some information in header of report are missing #2380
- [x] use movement reference (SM.x.y) instead of (DO.x) #2382
- [x] delete an inventory #2375 
- [x] filter stock movements by user #2384

**Comment by lomamech** [comment]
- [x] Display problem with the Inventories in Stock module just because there should not be the quantity to order as long as the initial stock is not yet distributed #2385
![issue2](https://user-images.githubusercontent.com/8035588/33831785-c37d4f2e-de79-11e7-80b9-ca72d9d853d5.png)

**Comment by jniles** [comment]
Looks like all these issues were addressed.
