### ISSUE TITLE
Add logic to show assets scans for specific Required Inventory Scans

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6481]
Add functions to the Required Inventory Scans registry action menu for specific items that will list items to be scanned, etc.

Functions to add to the Required Inventory Scans registry
- [x] Show all assets to be scanned on the Assets Registry page (scan date between start/end dates, filter on depot, reference_number)
- [x] Show all assets already scanned on the Assets Scans Registry page
- [x] Show all assets needing scanning on the Asset Registry page (scan date NOT between start/end dates, filter on depot, reference_number)

Additions needed:
- [x] ~~Add scan date to Assets Registry page with custom search filter for it.~~  Moved to [Issue 6536](https://github.com/IMA-WorldHealth/bhima/issues/6536)
- [x] Add custom filter for scan date on Asset Scans Registry page
