### ISSUE TITLE
(refactor) Cashbox Management

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#780]
The cashbox management page is terribly out of date.  Here is an incomplete list of issues with it.
- [x] Remove the unused utility bar.
- [x] Does not use `$state`-based routing.  The states should be broken down like this:
  - [x] `cashboxes/create` should open to the create form.
  - [x] `cashboxes/:uuid/update` should open the update form and load the cashbox matching `:uuid`.
  - [ ] ~~cashboxes/:uuid/currency/:id should open the update form for cashbox :uuid, and place the currency modal on top of it, open to currency id :did~~
    _(Linking the URL/ history for updating the currency of an individual cashbox would require nested state that we have not yet developed or used_
- [x] Submit and cancel buttons should [conform to standards](https://github.com/IMA-WorldHealth/bhima-2.X/issues/268).
- [x] Accounts should be `ui-select`s.  They were missed in #745.
- [x] Delete should use the confirm modal dialog (see #763).
- [x] **Bug** The cashbox does not register auxiliary versus primary on the edit page properly.

**Comment by jniles** [comment]
I'll look into this today.
